/**
 * One-time invite locator store.
 *
 * The server stores only the 80-bit routing locator. The 80-bit authentication
 * secret is generated by the creator's client and never sent to the relay.
 */
const { REDIS_URL, getRedisClient } = require('./redisClient');
const { parseEphemeralJson } = require('./ephemeralJson');

const INVITE_TTL_MS = 5 * 60 * 1000;
const CLEANUP_INTERVAL_MS = 30 * 1000;
const USE_REDIS = !!REDIS_URL;
const invites = new Map();
const INVITE_ALPHABET = '23456789ABCDEFGHJKLMNPQRSTUVWXYZ';

const KEYS = {
  invite: (locator) => `invite:${locator}`,
  inviteBySession: (sid) => `inviteBySession:${sid}`,
};

function generateInviteLocator() {
  const bytes = require('crypto').randomBytes(10);
  let bits = 0;
  let bitCount = 0;
  let body = '';
  for (const byte of bytes) {
    bits = (bits << 8) | byte;
    bitCount += 8;
    while (bitCount >= 5) {
      bitCount -= 5;
      body += INVITE_ALPHABET[(bits >>> bitCount) & 31];
      bits &= (1 << bitCount) - 1;
    }
  }
  return `TALK-${body.match(/.{4}/g).join('-')}`;
}

async function createInvite(sessionId, socketId) {
  if (!USE_REDIS) {
    for (let attempt = 0; attempt < 20; attempt++) {
      const locator = generateInviteLocator();
      if (!invites.has(locator)) {
        invites.set(locator, { sessionId, socketId, createdAt: Date.now() });
        return locator;
      }
    }
    throw new Error('Failed to allocate invite locator');
  }

  const client = await getRedisClient();
  for (let attempt = 0; attempt < 20; attempt++) {
    const locator = generateInviteLocator();
    const data = { sessionId, socketId, createdAt: Date.now() };
    const created = await client.set(KEYS.invite(locator), JSON.stringify(data), {
      NX: true,
      PX: INVITE_TTL_MS,
    });
    if (created) {
      await client.set(KEYS.inviteBySession(sessionId), locator, { PX: INVITE_TTL_MS });
      return locator;
    }
  }
  throw new Error('Failed to allocate invite locator');
}

async function getInvite(locator) {
  if (!USE_REDIS) {
    const invite = invites.get(locator);
    if (!invite) return null;
    if (Date.now() - invite.createdAt > INVITE_TTL_MS) {
      invites.delete(locator);
      return null;
    }
    return invite;
  }
  const client = await getRedisClient();
  const raw = await client.get(KEYS.invite(locator));
  return parseEphemeralJson(raw);
}

/** Atomically consume a locator only if it still belongs to expectedSessionId. */
async function consumeInvite(locator, expectedSessionId) {
  if (!USE_REDIS) {
    const invite = invites.get(locator);
    if (!invite || invite.sessionId !== expectedSessionId) return null;
    invites.delete(locator);
    return invite;
  }

  const client = await getRedisClient();
  const raw = await client.eval(
    `local value = redis.call('GET', KEYS[1])
     if not value then return nil end
     local ok, decoded = pcall(cjson.decode, value)
     if not ok then return nil end
     if decoded.sessionId ~= ARGV[1] then return nil end
     redis.call('DEL', KEYS[1])
     redis.call('DEL', KEYS[2])
     return value`,
    {
      keys: [KEYS.invite(locator), KEYS.inviteBySession(expectedSessionId)],
      arguments: [expectedSessionId],
    }
  );
  return parseEphemeralJson(raw);
}

async function cancelInvite(sessionId) {
  if (!USE_REDIS) {
    for (const [locator, invite] of invites) {
      if (invite.sessionId === sessionId) {
        invites.delete(locator);
        return true;
      }
    }
    return false;
  }

  const client = await getRedisClient();
  const locator = await client.get(KEYS.inviteBySession(sessionId));
  if (!locator) return false;
  const multi = client.multi();
  multi.del(KEYS.inviteBySession(sessionId));
  multi.del(KEYS.invite(locator));
  await multi.exec();
  return true;
}

async function hasInvite(sessionId) {
  if (!USE_REDIS) {
    for (const invite of invites.values()) {
      if (invite.sessionId === sessionId) return true;
    }
    return false;
  }
  const client = await getRedisClient();
  return !!(await client.get(KEYS.inviteBySession(sessionId)));
}

/** Dev/memory helper: put an invite back after a failed room claim. */
async function _restoreInvite(locator, invite) {
  if (USE_REDIS || !invite) return false;
  if (invites.has(locator)) return false;
  invites.set(locator, {
    sessionId: invite.sessionId,
    socketId: invite.socketId,
    createdAt: invite.createdAt || Date.now(),
  });
  return true;
}

async function cleanupExpiredInvites() {
  if (USE_REDIS) return;
  const now = Date.now();
  for (const [locator, invite] of invites) {
    if (now - invite.createdAt > INVITE_TTL_MS) invites.delete(locator);
  }
}

if (!USE_REDIS) {
  const cleanupTimer = setInterval(() => cleanupExpiredInvites().catch((err) => {
    console.error('Invite cleanup failed:', err?.message || err);
  }), CLEANUP_INTERVAL_MS);
  cleanupTimer.unref();
}

module.exports = {
  createInvite,
  getInvite,
  consumeInvite,
  cancelInvite,
  hasInvite,
  cleanupExpiredInvites,
  INVITE_TTL_MS,
  generateInviteLocator,
  _restoreInvite,
};
