/**
 * sessions.js - Session Store (Memory or Redis)
 *
 * ANONYMITY GUARANTEE:
 * - Sessions live only in memory (process RAM or Redis RAM).
 * - No disk writes, no persistence required.
 * - Session IDs are never logged or persisted.
 */

const { REDIS_URL, getRedisClient } = require('./redisClient');
const { parseEphemeralJson } = require('./ephemeralJson');

const SESSION_TTL_MS = 30 * 60 * 1000; // 30 minutes max session lifetime
const REDIS_KEY_TTL_MS = SESSION_TTL_MS + 2 * 60 * 1000;
const CLEANUP_INTERVAL_MS = 60 * 1000; // Sweep every 60 seconds

const USE_REDIS = !!REDIS_URL;
const sessions = new Map();
let expireHandler = null;

const KEYS = {
  session: (id) => `sess:${id}`,
  sessionBySocket: (sid) => `sessBySocket:${sid}`,
  createdZ: 'sess:created',
};

/**
 * Register a new anonymous session.
 * @param {string} sessionId - UUID v4 generated by the server
 * @param {string} socketId - Socket.IO socket ID
 */
async function addSession(sessionId, socketId) {
  const createdAt = Date.now();
  if (!USE_REDIS) {
    sessions.set(sessionId, {
      socketId, roomId: null, publicKey: null, keyConfirmed: false, createdAt,
    });
    return;
  }

  const client = await getRedisClient();
  const data = { socketId, roomId: null, publicKey: null, keyConfirmed: false, createdAt };
  const multi = client.multi();
  multi.set(KEYS.session(sessionId), JSON.stringify(data), { PX: REDIS_KEY_TTL_MS });
  multi.set(KEYS.sessionBySocket(socketId), sessionId, { PX: REDIS_KEY_TTL_MS });
  multi.zAdd(KEYS.createdZ, [{ score: createdAt, value: sessionId }]);
  multi.pExpire(KEYS.createdZ, REDIS_KEY_TTL_MS);
  await multi.exec();
}

/**
 * Remove a session permanently from memory.
 * After this call, no trace of the session exists.
 */
async function removeSession(sessionId) {
  if (!USE_REDIS) {
    sessions.delete(sessionId);
    return;
  }

  const client = await getRedisClient();
  const raw = await client.get(KEYS.session(sessionId));
  const data = parseEphemeralJson(raw);
  const multi = client.multi();
  multi.del(KEYS.session(sessionId));
  multi.zRem(KEYS.createdZ, sessionId);
  if (data?.socketId) {
    multi.del(KEYS.sessionBySocket(data.socketId));
  }
  await multi.exec();
}

/**
 * Get session data. Returns undefined if session doesn't exist.
 */
async function getSession(sessionId) {
  if (!USE_REDIS) {
    return sessions.get(sessionId);
  }
  const client = await getRedisClient();
  const raw = await client.get(KEYS.session(sessionId));
  return parseEphemeralJson(raw);
}

/**
 * Assign a room to a session.
 */
async function setSessionRoom(sessionId, roomId) {
  if (!USE_REDIS) {
    const session = sessions.get(sessionId);
    if (session) session.roomId = roomId;
    return;
  }

  const client = await getRedisClient();
  const raw = await client.get(KEYS.session(sessionId));
  if (!raw) return;
  const data = parseEphemeralJson(raw);
  if (!data) return;
  data.roomId = roomId;
  await client.set(KEYS.session(sessionId), JSON.stringify(data), { PX: REDIS_KEY_TTL_MS });
}

/**
 * Clear room assignment from a session.
 */
async function clearSessionRoom(sessionId) {
  if (!USE_REDIS) {
    const session = sessions.get(sessionId);
    if (session) session.roomId = null;
    return;
  }

  const client = await getRedisClient();
  const raw = await client.get(KEYS.session(sessionId));
  if (!raw) return;
  const data = parseEphemeralJson(raw);
  if (!data) return;
  data.roomId = null;
  await client.set(KEYS.session(sessionId), JSON.stringify(data), { PX: REDIS_KEY_TTL_MS });
}

/** Store the session's relayed public key (routing metadata only). */
async function setSessionPublicKey(sessionId, publicKey) {
  if (!USE_REDIS) {
    const session = sessions.get(sessionId);
    if (session) {
      session.publicKey = publicKey;
      session.keyConfirmed = false;
    }
    return;
  }

  const client = await getRedisClient();
  await client.eval(
    `local raw = redis.call('GET', KEYS[1])
     if not raw then return 0 end
     local ok, session = pcall(cjson.decode, raw)
     if not ok then return 0 end
     session.publicKey = ARGV[1]
     session.keyConfirmed = false
     redis.call('SET', KEYS[1], cjson.encode(session), 'PX', ARGV[2])
     return 1`,
    {
      keys: [KEYS.session(sessionId)],
      arguments: [publicKey, String(REDIS_KEY_TTL_MS)],
    }
  );
}

/** Record that this client sent a room-bound encrypted key proof. */
async function setSessionKeyConfirmed(sessionId) {
  if (!USE_REDIS) {
    const session = sessions.get(sessionId);
    if (session?.publicKey) session.keyConfirmed = true;
    return;
  }

  const client = await getRedisClient();
  await client.eval(
    `local raw = redis.call('GET', KEYS[1])
     if not raw then return 0 end
     local ok, session = pcall(cjson.decode, raw)
     if not ok or not session.publicKey or session.publicKey == cjson.null then return 0 end
     session.keyConfirmed = true
     redis.call('SET', KEYS[1], cjson.encode(session), 'PX', ARGV[1])
     return 1`,
    {
      keys: [KEYS.session(sessionId)],
      arguments: [String(REDIS_KEY_TTL_MS)],
    }
  );
}

/** Clear the session public key (new match / invite flow). */
async function clearSessionPublicKey(sessionId) {
  if (!USE_REDIS) {
    const session = sessions.get(sessionId);
    if (session) {
      session.publicKey = null;
      session.keyConfirmed = false;
    }
    return;
  }

  const client = await getRedisClient();
  await client.eval(
    `local raw = redis.call('GET', KEYS[1])
     if not raw then return 0 end
     local ok, session = pcall(cjson.decode, raw)
     if not ok then return 0 end
     session.publicKey = cjson.null
     session.keyConfirmed = false
     redis.call('SET', KEYS[1], cjson.encode(session), 'PX', ARGV[1])
     return 1`,
    {
      keys: [KEYS.session(sessionId)],
      arguments: [String(REDIS_KEY_TTL_MS)],
    }
  );
}

/** Atomically claim two idle sessions for a room. */
async function claimSessionRooms(sessionId1, sessionId2, roomId) {
  if (!USE_REDIS) {
    const first = sessions.get(sessionId1);
    const second = sessions.get(sessionId2);
    if (!first || !second || first.roomId || second.roomId) return false;
    first.roomId = roomId;
    second.roomId = roomId;
    return true;
  }

  const client = await getRedisClient();
  const claimed = await client.eval(
    `local raw1 = redis.call('GET', KEYS[1])
     local raw2 = redis.call('GET', KEYS[2])
     if not raw1 or not raw2 then return 0 end
     local ok1, first = pcall(cjson.decode, raw1)
     local ok2, second = pcall(cjson.decode, raw2)
     if not ok1 or not ok2 then return 0 end
     if first.roomId ~= cjson.null or second.roomId ~= cjson.null then return 0 end
     first.roomId = ARGV[1]
     second.roomId = ARGV[1]
     redis.call('SET', KEYS[1], cjson.encode(first), 'PX', ARGV[2])
     redis.call('SET', KEYS[2], cjson.encode(second), 'PX', ARGV[2])
     return 1`,
    {
      keys: [KEYS.session(sessionId1), KEYS.session(sessionId2)],
      arguments: [roomId, String(REDIS_KEY_TTL_MS)],
    }
  );
  return Number(claimed) === 1;
}

/**
 * Find session ID by socket ID.
 */
async function getSessionBySocketId(socketId) {
  if (!USE_REDIS) {
    for (const [sessionId, data] of sessions) {
      if (data.socketId === socketId) return sessionId;
    }
    return null;
  }

  const client = await getRedisClient();
  return await client.get(KEYS.sessionBySocket(socketId));
}

/**
 * Get total active session count (for health checks only).
 */
async function getSessionCount() {
  if (!USE_REDIS) {
    return sessions.size;
  }
  const client = await getRedisClient();
  return await client.zCard(KEYS.createdZ);
}

/**
 * TTL cleanup - removes expired sessions.
 * This ensures no session lingers in memory beyond its TTL.
 */
async function cleanupExpiredSessions() {
  const now = Date.now();

  if (!USE_REDIS) {
    const expired = [];
    for (const [sessionId, data] of sessions) {
      if (now - data.createdAt > SESSION_TTL_MS) {
        expired.push({ sessionId, socketId: data.socketId, roomId: data.roomId });
        sessions.delete(sessionId);
      }
    }
    if (expired.length && typeof expireHandler === 'function') {
      await expireHandler(expired);
    }
    return expired;
  }

  const client = await getRedisClient();
  const threshold = now - SESSION_TTL_MS;
  const expiredIds = await client.zRangeByScore(KEYS.createdZ, 0, threshold);
  if (!expiredIds.length) return [];

  const rawList = await client.mGet(expiredIds.map((id) => KEYS.session(id)));
  const expired = [];
  for (let i = 0; i < expiredIds.length; i++) {
    const raw = rawList[i];
    if (raw) {
      const data = parseEphemeralJson(raw);
      expired.push({
        sessionId: expiredIds[i],
        socketId: data?.socketId || null,
        roomId: data?.roomId || null,
      });
    } else {
      expired.push({ sessionId: expiredIds[i], socketId: null, roomId: null });
    }
  }

  const multi = client.multi();
  for (const id of expiredIds) {
    multi.del(KEYS.session(id));
    multi.zRem(KEYS.createdZ, id);
  }
  for (const entry of expired) {
    if (entry.socketId) multi.del(KEYS.sessionBySocket(entry.socketId));
  }
  await multi.exec();

  if (expired.length && typeof expireHandler === 'function') {
    await expireHandler(expired);
  }
  return expired;
}

// Start periodic cleanup
const cleanupTimer = setInterval(() => {
  cleanupExpiredSessions().catch((err) => {
    console.error('Session cleanup error:', err?.message || err);
  });
}, CLEANUP_INTERVAL_MS);
// Allow Node.js to exit even if timer is running
cleanupTimer.unref();

/**
 * Register a handler for expired sessions.
 * The handler receives an array of { sessionId, socketId, roomId }.
 */
function setExpireHandler(fn) {
  expireHandler = fn;
}

module.exports = {
  addSession,
  removeSession,
  getSession,
  setSessionRoom,
  clearSessionRoom,
  setSessionPublicKey,
  setSessionKeyConfirmed,
  clearSessionPublicKey,
  claimSessionRooms,
  getSessionBySocketId,
  getSessionCount,
  cleanupExpiredSessions,
  setExpireHandler,
  SESSION_TTL_MS,
  REDIS_KEY_TTL_MS,
};
